**About** 

In [ ]:
# Numpy : Numerical Python, written in partially python & most in C, C++
# NumPy array is almost 50X faster than python list

**Load & Check Version**

In [2]:
import numpy as np

In [5]:
print(np.__version__)

2.3.3


**Creating NumPy Arrays**

In [6]:
from_list = np.array([1,2,3,4])
from_list

array([1, 2, 3, 4])

In [7]:
from_tuple = np.array((1, 2, 3, 4))
from_tuple

array([1, 2, 3, 4])

**Difference with Python List**

In [ ]:
# Difference with python list

py_list = [1, 2, 3, 4, 5]
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
np_arr = np.array([1, 2, 3, 4, 5])  # Passing List
np_arr*2  # vectorized operation

array([ 2,  4,  6,  8, 10])

In [ ]:
# Checking object type
print(type(np_arr))

<class 'numpy.ndarray'>


In [8]:
from_tuple*2

array([2, 4, 6, 8])

**Dimensions in Arrays & ndim, ndmin**

In [ ]:
arr = np.array(87)

print(arr)
print(arr.ndim)  # check dimension

87
0


In [12]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 8]])

print(arr)
print(arr.ndim)

[[1 2 3 4]
 [4 5 6 8]]
2


In [15]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
# with these elements create 5 dimensional array
print(arr)
print(f"Dimension of arr: {arr.ndim}")

[[[[[1 2 3 4 5]]]]]
Dimension of arr: 5


**Indexing**

In [16]:
arr = np.array([1, 2, 3, 4])
print(arr[1])
print(arr[2] + arr[3])

2
7


In [ ]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 8], [9, 10, 11, 12]])
print(arr[1][3])
print(arr[1, 3])  # recommended to use

8
8


In [26]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
# Step by Step:
print(f"At arr[0]: {arr[0]}")
print(f"At arr[0, 1]: {arr[0, 1]}")
print(f"At arr[0, 1, 2]: {arr[0, 1, 2]}")

6
At arr[0]: [[1 2 3]
 [4 5 6]]
At arr[0, 1]: [4 5 6]
At arr[0, 1, 2]: 6


In [28]:
# Suppose we wanna access 11 with all negative indexing
print(arr[-1, -1, -2]) 

11


**Slicing**

In [34]:
# Same as string slicing in Python
# [start:end:step] -> 'start' included and 'end' excluded

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0:5]) # printing 1 to 5
print(arr[:4])  # starting to index 3
print(arr[1::2])# only even numbers

[1 2 3 4 5]
[1 2 3 4]
[2 4 6]


In [40]:
# Same task with negative slicing
print(arr[:-1])
print(arr[:-2])
print(arr[::-1]) # reverse array

[1 2 3 4 5]
[1 2 3 4]
[6 5 4 3 2 1]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # accessing 7, 8, 9

[7 8 9]


In [42]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])
# That's a 3x3 matrix suppose we wanna choose the submatrix [[3,4], [8,9]]
print(arr[0:2, 2:4])

[[3 4]
 [8 9]]


In [ ]:
# Shifting both rows and columns
print(arr[::-1, ::-1])

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


**Arithmatic Operations**

In [51]:
arr = np.array([1, 2, 3, 4, 5])

print(arr**2)
print(np.sqrt(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1 + arr2)
print(arr2 - arr1)
print(arr2 * arr1)
print(arr2 / arr1)
print(arr1 ** arr2)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[    1    64  2187 65536]


In [53]:
# Suppose, we have a list of radius (Circle) arrays and we need to calculate Area
radii = np.array([1, 1.2, 3.4, 6.8, 3])
area = np.pi * radii**2
print(area)

[  3.14159265   4.52389342  36.31681108 145.2672443   28.27433388]


In [54]:
marks = np.array([24, 35, 76, 85, 60, 95, 31])
passed = marks >= 33
print(passed)

[False  True  True  True  True  True False]


In [58]:
# if no of students needed
print(f"{len(passed[passed==False])} students failed.")
# OR,
print(f"{len(marks[marks < 33])} students failed.")

2 students failed.
2 students failed.


In [67]:
# Print passed students marks 
print(marks[passed])

[35 76 85 60 95]


**Broadcasting**

In [70]:
# It is possible in NumPy to multiply a 4x1 and 4x4 although they're not Comparable
arr1 = np.array([[1], 
                 [2], 
                 [3], 
                 [4]]) 
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
print(arr1 * arr2)
print(arr2 * arr1)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [ ]:
# But these types of operations can only be done in two cases - 
# Either the dimension must be same or one dimension have to 1
# like if the dims (4,1) & (4,2) -> not possible bcz row 4 and 4 match but in column 4 and 2 doesn't satisfy any condition
# (4,1) & (1,4) ; (4,1) & (4,4) can be done because both satisfy the condition
# Check shape: 
print(arr1.shape)  # returns a tuple
print(arr2.shape)

(4, 1)
(4, 4)


In [73]:
# Error 
arr1 = np.array([[1], 
                 [2], 
                 [3]]) 
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
print(arr1.shape)
print(arr2.shape)
# print(arr1 * arr2)
# print(arr2 * arr1)

(3, 1)
(4, 4)


In [ ]:
# Row: 3 and 4 -> doesn't satisfy any condition ,neither match nor one is 1
# Col: 1 and 4 -> satisfy, either not same but one is 1
# Overall, the operation isn't possible bcz Row's dimenstion contradicts.

**Aggregate Function**

In [95]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))  # standard deviation
print(np.var(array))  # variance

36
4.5
2.29128784747792
5.25


In [98]:
print(np.min(array))
print(np.argmin(array))  # min on which index
print(np.max(array))
print(np.argmax(array))  # max on which index

1
0
8
7


In [100]:
# Sum of all columns
print(np.sum(array, axis= 0))
# Sum of all rows
print(np.sum(array, axis= 1))

[ 6  8 10 12]
[10 26]


In [84]:
from IPython.display import Image, display
print("Variance: ")
display(Image(url="https://media.geeksforgeeks.org/wp-content/uploads/var.jpg"))
print("Standard Deviation: ")
display(Image(url="https://www.nlm.nih.gov/oet/ed/stats/img/SDFormula.png"))

Variance: 


Standard Deviation: 


**Array Joining Methods**

In [201]:
_arr1 = [1, 2, 3, 4]
_arr2 = [5, 6, 7, 8]
new_arr = np.concatenate((_arr1,_arr2))
print(new_arr)

[1 2 3 4 5 6 7 8]


In [ ]:
_arr1 = [[1, 2], [3, 4]]
_arr2 = [[5, 6], [7, 8]]
# new_arr = np.concatenate((_arr1,_arr2)) 
new_arr = np.concatenate((_arr1,_arr2), axis=1) # along rows
print(new_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Stacking -> combining multiple arrays together along a specified axis.
# Creats new dimension
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)  # by default, axis=0 -> [1,2,3][4,5,6] (shape- (2, 3))

print(arr) # shape(3, 2)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Stacking along rows
arr = np.hstack((arr1, arr2)) # horizontal stack
print(arr)

[1 2 3 4 5 6]


In [208]:
# Stacking along columns
arr = np.vstack((arr1, arr2)) # vertical stack
print(arr)

[[1 2 3]
 [4 5 6]]


In [209]:
# Stacking along height 
arr = np.dstack((arr1, arr2)) # depth stack
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# Suppose we have student data in separate arrays and we wanna combine them
names = np.array(["A", "B", "C"])
marks = np.array([80, 90, 85])
combined = np.column_stack((names, marks))
# combined = np.stack((names, marks), axis=1)
print(combined)

[['A' '80']
 ['B' '90']
 ['C' '85']]


**Iteration, Split, Search, Sort**

In [ ]:
# Iterate over each 2D array element
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterate over 3D array -> will go upto 2 dimension
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
# If we wanna iterate over each element we need 3 nested loop; so time consuming

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):  # replacement of 3 nested loop
  print(x)

1
2
3
4
5
6
7
8


In [257]:
# We can also iterate as a different data-type
arr = np.array([1, 2, 3, 4])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

# Easier way : 
print("Easier way: ")
str_arr = arr.astype("S")
for x in np.nditer(str_arr):
  print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
Easier way: 
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [245]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,::2]):
    print(x)


1
3
5
7


In [246]:
# Enumerated Iteration
for idx, element in np.ndenumerate(arr):
    print(idx, element)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [215]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
new_arr = np.array_split(arr,4) # split(arr, 4) would fail here
print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [218]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [220]:
# Split along columns 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3) # opposite of vstack()
newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
newarr = np.hsplit(arr, 3) # opposite of hstack()
newarr
# dsplit() also available

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:
# Search where(at which index(s)) the value is
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
x
# 4 is present at the index 3, 5 and 6

(array([3, 5, 6]),)

In [ ]:
# searchsorted() -> performs binary search, so only on sorted arrays
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7) # Find where 7 should be inserted
print(x)
x = np.searchsorted(arr, 7, side='right')
print(x)  # index from right

1
2


In [233]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6]) # find where 2, 4, 6 should be inserted
print(x)

[1 2 3]


In [240]:
# Sort a 1D array
arr = np.array([12, 87, 43, 8, 102, 10])
sorted_arr = np.sort(arr)
print(f"Sorted Array: {sorted_arr}")
print(f"Original Array: {arr}")  # unchanged

Sorted Array: [  8  10  12  43  87 102]
Original Array: [ 12  87  43   8 102  10]


In [237]:
# Sort a 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
# Sort a boolean array
arr = np.array([True, True, False, False, True]) # lexicographically
print(np.sort(arr))

[False False  True  True  True]


**Data Types**

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
arr = np.array(['banana', 'mango', 'litchi'])
print(arr.dtype) # Unicode String with max length 6

int64
<U6


In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype= "S")
print(arr)
print(arr.dtype) # S1 -> Byte String with length 1

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
# Value Error -> 'a' can't be converted to integer
arr = np.array(['1', '2', '3', 'a'], dtype= 'i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [92]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int) # arr.astype('i') also valid
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [101]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


**Copy vs View**

In [ ]:
# The copy is a new array, and the view is just a view of the original array.

In [103]:
# The copy owns the data and any changes made to the copy will not affect original array, 
# and any changes made to the original array will not affect the copy.

arr = np.array([1, 2, 3, 4, 5])
copyArr = arr.copy()
arr[2] = 69
copyArr[0] = 87
print(arr)
print(copyArr)

[ 1  2 69  4  5]
[87  2  3  4  5]


In [104]:
# The view does not own the data and any changes made to the view will affect the original array, 
# and any changes made to the original array will affect the view.

arr = np.array((10, 20, 30, 40, 50))
viewArr = arr.view()
arr[3] = 98
viewArr[2] = 24
print(arr)
print(viewArr)

[10 20 24 98 50]
[10 20 24 98 50]


**Reshaping Arrays**

In [ ]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
newArr = arr.reshape(2, 3)
print(newArr)
print(newArr.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [106]:
# 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# But we can't transform dimension as our wish, like in the 2nd example..
# we can't to make (2, 4, 2) or (2, 3, 3) bcz with the 12 elements at most 12 (2*3*2)
# cells can be filled not more than this, to fill 2*4*2 cells need min. 16 elements

In [ ]:
# We can use unknown dimension
newarr = arr.reshape(2, 2, -1) # We can not pass -1 to more than one dimension.
print(newarr)
print(newArr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 3)


In [111]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
print(newArr.shape)

[1 2 3 4 5 6]
(2, 3)


**Filtering**

In [115]:
# We wanna filter out teenagers, milk-babies & senior citizens
ages = np.array([[12, 34, 87, 14, 9],
                 [32, 76, 11, 16, 98],
                 [56, 9, 13, 2, 1]])
milk_babies = ages[ages<=3]
teenagers = ages[(ages>10) & (ages<18)]
senior_citizens = ages[ages>=60]
print(f"There are {len(milk_babies)} milk-babies and their age: {milk_babies}")
print(f"{len(teenagers)} teenagers and their age: {teenagers}")
print(f"{len(senior_citizens)} seinor-citizens and their age: {senior_citizens}")


There are 2 milk-babies and their age: [2 1]
5 teenagers and their age: [12 14 11 16 13]
3 seinor-citizens and their age: [87 76 98]


In [120]:
# Find how many voters, print their age and set non-voters age to 0
voters = np.where(ages >= 18, ages, 0)
print(f"Total voters count: {len(voters)} and their age: {voters[voters != 0]}")
print(voters)

Total voters count: 3 and their age: [34 87 32 76 98 56]
[[ 0 34 87  0  0]
 [32 76  0  0 98]
 [56  0  0  0  0]]


In [ ]:
# Create an array from the elements on index 1(10) and 3(102)
arr = np.array([43, 10, 8, 102, 87])
bool_index = [False, True, False, True, False]
newArr = arr[bool_index]
print(newArr)

[ 10 102]


In [199]:
# Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filtered_arr = []
for element in arr: # without hardcoding the boolean values in filtered_arr
    if element % 2 == 0 :
        filtered_arr.append(True)
    else :
        filtered_arr.append(False)
newArr = arr[filtered_arr]
print(newArr)
# Directly :
print(arr[arr % 2==0])

[2 4 6]
[2 4 6]


**Random Numbers**

In [130]:
# Generating random integers
rng = np.random.default_rng()
rand_num = rng.integers(1, 11) # range: 1- 10
print(rand_num)

3


In [140]:
rand_num = rng.integers(low=1, high=100, size=2)  # by default, size=1
print(rand_num)

[ 3 12]


In [139]:
rand_matrix = rng.integers(low=1, high=101, size=[4,3]) # a 4x3 matrix
print(rand_matrix)

[[19 38 52]
 [57 63 38]
 [54 69 97]
 [19 50 39]]


In [ ]:
# Use of seed -> reproduce same sequenced numbers (same on every run)
rng = np.random.default_rng(seed=1)
rand_matrix = rng.integers(low=1, high=101, size=[4,3]) # a 4x3 matrix
print(rand_matrix)

[[48 52 76]
 [96  4 15]
 [83 95 25]
 [32 87 43]]


In [ ]:
# Generate random float values (all same thing can be applied here also)
rand_float = np.random.uniform() # Uniform Distribution
print(rand_float)

0.8015198825847796


In [155]:
rand_float = np.random.uniform(low=1, high=11)
print(rand_float)
rand_mat = np.random.uniform(-100, 101, size=[3,8])
print(rand_mat)

6.127553545938023
[[ 81.35409179  45.52720808  33.84441655  -0.62661362 -95.24519841
  -64.37829753  87.4253949   -6.55867132]
 [-50.00345364 -47.70845735 -34.85344375  31.13000109  21.07599197
   -3.38454304 -88.78662253 -19.00618534]
 [ 76.52745307 -72.91416439  19.97099133  62.39383279 -68.87104739
   88.56335294 -86.96689207  48.82630199]]


In [168]:
# Shuffling arrays
rng = np.random.default_rng()
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
rng.shuffle(arr)
print(arr)

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [173]:
# Random choice from arrays
names = np.array(["Alexa", "Siri", "Badhon", "Horseman"])
name = rng.choice(names)
print(name)

Badhon


In [181]:
choosen_names = rng.choice(names, size=2)
print(choosen_names)
choosen_names = rng.choice(names, size=(2,3))
print(choosen_names)

['Badhon' 'Siri']
[['Horseman' 'Horseman' 'Siri']
 ['Horseman' 'Badhon' 'Alexa']]


In [ ]:
emojis = np.array(["😑","🤩","🤗","🥰","🤣","😎","😊","😘","🥵","🥸"]) 
emoji = rng.choice(emojis) # Win + ; -> to select emojis
print(emoji)

🥵
